# Generated by Django 3.2.6 on 2021-09-02 00:43

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf_ou_cnpj', models.CharField(max_length=14)),
                ('nome_fantasia', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=60)),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=60)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('forma_pagamento', models.IntegerField(choices=[(1, 'AVISTA'), (2, 'APRAZO'), (3, 'CARTAO_CREDITO'), (4, 'CARTAO_DEBITO'), (5, 'PIX'), (6, 'GESTOR_FROTAS')])),
                ('tipo_veiculo', models.IntegerField(choices=[(1, 'MOTO'), (2, 'CARRO'), (3, 'CAMINHONETE'), (4, 'CAMINHAO'), (5, 'ONIBUS')], default=app.models.TipoVeiculo['CARRO'])),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.IntegerField(choices=[(1, 'MOTO'), (2, 'CARRO'), (3, 'CAMINHONETE'), (4, 'CAMINHAO'), (5, 'ONIBUS')], default=app.models.TipoVeiculo['CARRO'])),
                ('placa', models.CharField(max_length=7)),
                ('descricao', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.tiposervico')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField()),
                ('numero_nota', models.CharField(max_length=60)),
                ('codigo_verificacao', models.CharField(max_length=60)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.IntegerField(choices=[(1, 'AGUARDANDO_LAVAGEM'), (2, 'LAVAGEM_ANDAMENTO'), (3, 'AGUARDANDO_LIMPEZA'), (4, 'LIMPEZA_ANDAMENTO'), (5, 'FINALIZADO'), (6, 'ENTREGUE')], default=app.models.ServicoStatus['AGUARDANDO_LAVAGEM'])),
                ('itens', models.ManyToManyField(to='app.ServicoItem')),
            ],
        ),
    ]
