# Generated by Django 4.0.2 on 2022-02-04 01:17

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf_ou_cnpj', models.CharField(max_length=14, verbose_name='CPF/CNPJ')),
                ('nome_fantasia', models.CharField(max_length=60, verbose_name='Nome fantasia')),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=60, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('complemento', models.CharField(blank=True, default='', max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(blank=True, default='', max_length=60, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tipo_veiculo', models.IntegerField(choices=[(1, 'MOTO'), (2, 'CARRO'), (3, 'CAMINHONETE'), (4, 'CAMINHAO'), (5, 'ONIBUS')], default=app.models.TipoVeiculo['CARRO'], verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.IntegerField(choices=[(1, 'MOTO'), (2, 'CARRO'), (3, 'CAMINHONETE'), (4, 'CAMINHAO'), (5, 'ONIBUS')], default=app.models.TipoVeiculo['CARRO'], verbose_name='Tipo')),
                ('placa', models.CharField(max_length=7)),
                ('descricao', models.CharField(blank=True, default='', max_length=50, verbose_name='Descrição')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(verbose_name='Entrada')),
                ('data_saida', models.DateTimeField(verbose_name='Saída')),
                ('numero_nota', models.CharField(blank=True, default='', max_length=60, verbose_name='N° da nota')),
                ('codigo_verificacao', models.CharField(blank=True, default='', max_length=60, verbose_name='Código de verificação')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Desconto')),
                ('forma_pagamento', models.IntegerField(choices=[(1, 'AVISTA'), (2, 'APRAZO'), (3, 'CARTAO_CREDITO'), (4, 'CARTAO_DEBITO'), (5, 'PIX'), (6, 'GESTOR_FROTAS')], verbose_name='Forma de pagamento')),
                ('status', models.IntegerField(choices=[(1, 'AGUARDANDO_LAVAGEM'), (2, 'LAVAGEM_ANDAMENTO'), (3, 'AGUARDANDO_LIMPEZA'), (4, 'LIMPEZA_ANDAMENTO'), (5, 'FINALIZADO'), (6, 'ENTREGUE')], default=app.models.ServicoStatus['AGUARDANDO_LAVAGEM'])),
                ('observacao', models.CharField(blank=True, default='', max_length=60, verbose_name='Observação')),
                ('itens', models.ManyToManyField(to='app.TipoServico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.veiculo', verbose_name='Veículo')),
            ],
        ),
    ]
