# Generated by Django 3.2.7 on 2021-12-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposervico',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='servico',
            name='forma_pagamento',
            field=models.IntegerField(choices=[(1, 'AVISTA'), (2, 'APRAZO'), (3, 'CARTAO_CREDITO'), (4, 'CARTAO_DEBITO'), (5, 'PIX'), (6, 'GESTOR_FROTAS')], default=0, verbose_name='Forma de pagamento'),
            preserve_default=False,
        ),
    ]
