# Generated by Django 3.2.7 on 2021-12-10 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211209_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='veiculo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='app.veiculo'),
            preserve_default=False,
        ),
    ]
