# Generated by Django 4.0.2 on 2022-03-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_acerto_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
