# Generated by Django 4.0.2 on 2022-03-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_servico_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='acerto',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='acerto',
            name='forma_pagamento',
            field=models.IntegerField(choices=[(1, 'AVISTA'), (2, 'APRAZO'), (3, 'CARTAO_CREDITO'), (4, 'CARTAO_DEBITO'), (5, 'PIX'), (6, 'GESTOR_FROTAS')], default=0, verbose_name='Forma de pagamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acerto',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999, verbose_name='Valor da comissão'),
        ),
    ]
