# Generated by Django 4.0.2 on 2022-04-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_servico_desconto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acerto',
            name='desconto',
        ),
        migrations.AddField(
            model_name='servico',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Desconto'),
        ),
    ]
