# Generated by Django 4.0.5 on 2022-11-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_servico_acrescimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='pago',
        ),
    ]
